# RiseEmpire Plugin Configuration

# Set the maximum number of totems a player can pop in a single life.
totem-limit: 2

# Enable or disable the bypass system entirely.
# If false, no players can bypass plugin restrictions.
enable-bypass: true

# List of player UUIDs who are exempt from all plugin restrictions (like totem limits).
# This list can be managed in-game with '/re bypass add/remove <player>'.
bypass-players:
  - "0ce3084b-540f-4f31-8ebb-dfee1b85bbdf"
